#!/bin/bash

# === Config ===
src='./src'
serverpid='./tool/.server_pid'
public='./public'
env=$1

# === Clean up ===
echo 'Cleaning ...'
[[ -e $public ]] && rm -r $public
mkdir -p $public/{css,js}
echo 'Killing the server...'
[[ -e $serverpid ]] && kill $(cat $serverpid)

# === Compile less ===
echo 'Compiling less...'
lessc -x $src/less/importer.less > $public/css/style.css

# === Compile mustache ===
echo 'Compiling mustache...'
hulk $src/mustache/*.mustache > $public/js/templates.js

# === Concatenate vendor js ===
echo 'Compiling js...'
cat $src/js/ender.js > $public/js/app.js
echo "(function (global) {" >> $public/js/app.js
cat $src/js/init.js >> $public/js/app.js
cat $public/js/templates.js >> $public/js/app.js
cat $src/js/boot.js >> $public/js/app.js
echo "}) (this);" >> $public/js/app.js

if [ "$env" = "prod" ]; then
   echo 'Uglifying js...'
   uglifyjs --overwrite $public/js/app.js
fi

# === html ===
echo 'Copying html...'
cp $src/index.html $public

# === server ===
echo 'Copying server...'
cp $src/http.js $public

# === init server ===
if [ $# == 0 ]; then
   echo 'Starting server...'
   node $public/http.js &
   echo $! > $serverpid
fi
