#!/bin/bash

# Usage 
#  $ watch directory interval command
#     directory: path to the directory to watch for changes
#     interval: integer, sets the polling time
#     command: script or command to be called when changes happen

dir=$1
interval=$2
cmd=$3
sum1=`find $dir -type f -exec md5 {} \;`
sum2=$sum1

echo "Watching $dir ..."
while [[ true ]]
do
   sum2=`find $dir -type f -exec md5 {} \;`
   if [[ $sum1 != $sum2 ]] ; then
      echo "Directory changed..."
      echo "Running $cmd ..."
      $cmd
      sum1=$sum2
   fi
   sleep $interval
done
